### ISSUE TITLE
Failing jest unit test due to import statement in sgds node module

### ISSUE THREAD

**Issue by suenalaba** [GovTechSG/sgds-govtech-react#202]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

Issue: 
When running jest unit tests:the following error occurs: Cannot use import statement outside a module

![Screenshot 2023-11-07 at 12 11 21 PM](https://github.com/GovTechSG/sgds-govtech-react/assets/61338348/31e71737-72a2-4365-8524-9b7227e5a9af)

How to reproduce?
Using import statement like this in my component: `import { Card } from '@govtechsg/sgds-react/Card';`

However, if we import the Card Component for example like this:
`import { Card } from '@govtechsg/sgds-react';`
The error goes away.

Both imports should be expected to work but it is not behaving as expected. The reason for wanting the import path as: 
`import { Card } from '@govtechsg/sgds-react/Card';`
is to reduce the bundle size.

Dependencies:
<img width="449" alt="Screenshot 2023-11-17 at 1 50 32 PM" src="https://github.com/GovTechSG/sgds-govtech-react/assets/61338348/0da78786-0991-404e-8dc4-9e6ebe676eb6">

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

"react": "^18", "@govtechsg/sgds-react": "^2.2.2"

**Comment by clukhei** [comment]
Hello @suenalaba , thanks for raising this. 

Jest support for [esm is still experimental](https://jestjs.io/docs/ecmascript-modules). Thus, there needs to be some configuration on your end in the jest.config.js file. 

In your jest.config.js file, in `transformIgnorePatterns` field ,change` /node_modules/` to this 
```
transformIgnorePatterns: [
    "/node_modules/(?!(@govtechsg/sgds-react)/)",
  ]
```

It means don't transform all of node_modules packages except @govtechsg/sgds-react. 
Let me know if this works for you :) 

If you try out Jest experimental mode and it works , do share it here !

**Comment by suenalaba** [comment]
We tried this method, however it doesn't work as well. The only way we made it work is by importing `import { Card } from '@govtechsg/sgds-react';` instead of `import { Card } from '@govtechsg/sgds-react/Card';`

**Comment by clukhei** [comment]
@suenalaba I have replicated the issue here and fixed it with same jest config and using `import { Card } from '@govtechsg/sgds-react/Card'`. 

EDIT: [codesandbox](https://codesandbox.io/p/github/clukhei/stackblitz-next-jest/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp7wsgpx00073b6g5scwuu41%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp7wsgpx00033b6gw96m9m6l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp7wsgpx00053b6gf7d1br5w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp7wsgpx00063b6glyqvtabu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp7wsgpx00033b6gw96m9m6l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp7wsgpw00023b6gwv2zu2pd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clp7wsgpx00033b6gw96m9m6l%2522%252C%2522activeTabId%2522%253A%2522clp7wsgpw00023b6gwv2zu2pd%2522%257D%252C%2522clp7wsgpx00063b6glyqvtabu%2522%253A%257B%2522id%2522%253A%2522clp7wsgpx00063b6glyqvtabu%2522%252C%2522activeTabId%2522%253A%2522clp7wsgsm000p3b6g90hatc5j%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clp7wsgsm000p3b6g90hatc5j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp7wtml800ch3b6gjc995b2x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clp7wsgpx00053b6gf7d1br5w%2522%253A%257B%2522id%2522%253A%2522clp7wsgpx00053b6gf7d1br5w%2522%252C%2522activeTabId%2522%253A%2522clp7wsgpx00043b6gnkwtrjxc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp7wsgpx00043b6gnkwtrjxc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp7wsgxa000pehg96r9o9fud%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clp7wshuf008d3b6g2198knv6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) link for easier viewing 
You can pull down this repo run test to try and see what's the difference to debug. Im using NEXT + JEST + babel
https://github.com/clukhei/stackblitz-next-jest

if you still cannot make it work, do provide me with a minimal reproducible repository.

**Comment by suenalaba** [comment]
We use `next/jest` to inject our next.config.js and .env into our test environment. However this causes the transform patterns to be overwritten, instead of extending it. Which causes the above method not to work. We got it to work with ```nextJestConfig.transformIgnorePatterns[0] = '/node_modules/(?!(@govtechsg/sgds-react)/)';``` instead.
