### ISSUE TITLE
Combobox dropdown arrow not triggering dropdown

### ISSUE THREAD

**Issue by clye-cog** [GovTechSG/sgds-govtech-react#270]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

The arrow icon of the dropdown isn't table to be clicked to trigger the menu
Reference: https://github.com/user-attachments/assets/f0448dee-7ca3-40db-9936-cebd0340c46c

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

NextJS, React, Typescript. sgds-react v 2.7.2

**Comment by clukhei** [comment]
@clye-cog The icon isnt meant to be a button to click, it serves more as an indication. When menuList is populated the dropdown list will appear when input is clicked or focused. When dropdown list is empty menuList is configured not to appear. 

I think this problem you faced is because of the bug logged in #271 and will be resolved once that is fixed.

**Comment by clukhei** [comment]
Since #271 is resolved i will closed this ticket
