### ISSUE TITLE
Combobox has issues filtering the typed out option

### ISSUE THREAD

**Issue by clye-cog** [GovTechSG/sgds-govtech-react#274]
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

The search filter seems to have broken when users type in their search term. Likely due to the recent `useEffect`?
https://github.com/GovTechSG/sgds-govtech-react/commit/15536f3f1e7aa65b1203e177ad6e6b30baee148d#diff-f72e213c646cd6fc3346d6737b54dd6072aa2ccfbd86fea842a8d3407fcc0340R181

Reference video: https://github.com/user-attachments/assets/5e7b016f-04c2-48c2-b1de-de75a0ea2559

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

NextJS Typescript React sgds-react v2.7.3

**Comment by clukhei** [comment]
Hi @clye-cog , 

the reason why the combobox menu doesnt look like its filtering is because the parent `<ComboboxComponent />` is calling `setFruits`. The parent re-renders every time the `fruits` state updates and it causes the child `<Combobox/>` to re-render and run the useEffect hook with menuList dependency every time it re-renders. 

To prevent child from running the useEffect hook with menuList dependency, you have to use `useMemo` on menuList.  This is only needed when the parent component is triggering updates. Since there are quite a few ways users will likely populate and optimise the menuList this is more of an application concern rather than a bug in the code. 

```
export const ComboboxOnChangeTemplate = () => {
  const [fruits, setFruits] = useState('');
  const handleChange = (val, e) => {
    setFruits(val);
  };
  const menuList = useMemo(() => ['apple', 'orange', 'banana'],[]);
  return (
    <>
      <Combobox
        menuList={menuList}
        onChangeInput={handleChange}
        label="Select a fruit"
        id="typeaheadExample"
        icon={<i className="bi bi-search"></i>}
      />
      <div>Selected fruits : {fruits}</div>
    </>
  );
};
```

have updated the documentation to include useMemo in the storybook example.

**Comment by clye-cog** [comment]
Hi @clukhei , thanks for the hard work and the update! 🙌 🌮
